/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 /tmp/scratch/petalinux-yocto/yocto_sdk_minimal_2017.2/build/tmp/sysroots/x86_64-linux/usr/bin/perl-native/perl5.22.1.real ../bin/enc2xs -Q -O -o ebcdic_t.c -f ebcdic_t.fnm
 enc2xs VERSION 2.17
*/
extern encode_t cp1026_encoding;
extern encode_t cp1047_encoding;
extern encode_t cp37_encoding;
extern encode_t cp500_encoding;
extern encode_t cp875_encoding;
extern encode_t posix_bc_encoding;
