/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 /tmp/scratch/petalinux-yocto/yocto_sdk_minimal_2017.2/build/tmp/sysroots/x86_64-linux/usr/bin/perl-native/perl5.22.1.real ../bin/enc2xs -Q -o bi_01_t.c -f bi_01_t.fnm
 enc2xs VERSION 2.17
*/
extern encode_t big5_hkscs_encoding;
