#!/usr/bin/perl

open (IOCTLS,'/tmp/scratch/petalinux-yocto/yocto_sdk_minimal_2017.2/build/tmp/sysroots/microblazeel-v10.0-bs-cmp-mh-div-generic/usr/include/sys/ioctl.h') || die "ioctl open failed";

while (<IOCTLS>) {
    if (/^\s*#\s*define\s+\w+\s+_IO(R|W|WR)\('?\w+'?,\s*\w+,\s*([^)]+)/) {
	$need{$2}++;
    } 
}

foreach $key ( sort keys %need ) {
    print $key,"\n";
} 
